---
title: ''
format:
  html:
    code-fold: true
    code-tools: true
---

::: panel-tabset

## Set-Up

```{r}
#| code-fold: false
suppressPackageStartupMessages({
  library(readxl)
  library(gtsummary)
  library(flextable)
  library(ggeffects)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(reshape2)
  library(stats)
  library(ordinal)
  library(texreg)
})

load("data/digital_distraction_data.RData")
```

## Internal Consistency 

#### Calculate Cronbach's alpha 

```{r, eval=FALSE}
calculate_alpha <- function(data, prefix) {
  category_cols <- grep(paste0("^", prefix), colnames(data), value = TRUE)
  alpha_result <- alpha(data[, category_cols])
  cat(paste("Cronbach's alpha for", prefix, ":", format(alpha_result$total$raw_alpha, digits = 2, nsmall = 2)), "\n")
  return(alpha_result)
}

data_filtered_pre <- data %>% filter(time == "0")

alpha_AI_pre <- calculate_alpha(data_filtered_pre, "AI")
alpha_OV_pre <- calculate_alpha(data_filtered_pre, "OV")
alpha_MT_pre <- calculate_alpha(data_filtered_pre, "MT")
alpha_ER_pre <- calculate_alpha(data_filtered_pre, "ER")

data_filtered_post <- data %>% filter(time == "1")

alpha_AI_post <- calculate_alpha(data_filtered_post, "AI")
alpha_OV_post <- calculate_alpha(data_filtered_post, "OV")
alpha_MT_post <- calculate_alpha(data_filtered_post, "MT")
alpha_ER_post <- calculate_alpha(data_filtered_post, "ER")
```

#### Attention Impulsiveness (AI)

```{r}
#| code-fold: false
alpha_AI_pre$total$raw_alpha %>% round(2)
```

```{r}
#| code-fold: false
alpha_AI_post$total$raw_alpha %>% round(2)
```

#### Online Vigilance (OV)

```{r}
#| code-fold: false
alpha_OV_pre$total$raw_alpha %>% round(2)
```

```{r}
#| code-fold: false
alpha_OV_post$total$raw_alpha %>% round(2)
```

#### Multitasking (MT)

```{r}
#| code-fold: false
alpha_MT_pre$total$raw_alpha %>% round(2)
```

```{r}
#| code-fold: false
alpha_MT_post$total$raw_alpha %>% round(2)
```

#### Emotion Regulation (ER)

```{r}
#| code-fold: false
alpha_ER_pre$total$raw_alpha %>% round(2)
```

```{r}
#| code-fold: false
alpha_ER_post$total$raw_alpha %>% round(2)
```

## Contingency Table 

```{r, eval=FALSE}
selected_data <- data %>% select(student, group, time, AI1:ER4)

long_data <- melt(selected_data, id.vars = c('student', 'group', 'time'), variable.name = 'question', value.name = 'response')

table <- long_data %>%
  mutate(time = case_when(
    time == "0" ~ "Pre-test",
    time == "1" ~ "Post-test"
    )) %>%
  mutate(time = factor(time, levels = c("Pre-test", "Post-test"))) %>% 
  mutate(group = case_when(
    group == "0" ~ "Control",
    group == "1" ~ "Treatment"
  )) %>%
  group_by(question, group, time, response) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  group_by(question, group, time) %>%
  mutate(Percentage = Count / sum(Count) * 100) %>%
  mutate(Freq_Percent = paste0(Count, " (", round(Percentage, 1), "%)")) %>%
  select(-Count, -Percentage) %>%
  pivot_wider(names_from = response, values_from = Freq_Percent, values_fill = list(Freq_Percent = "0 (0%)")) %>%
  ungroup()

table_flex <- table %>%
  flextable() %>%
  merge_v(j = ~ question) %>%
  merge_v(j = ~ group) %>%
  theme_vanilla() %>%
  autofit()
```

```{r}
#| code-fold: false
table_flex
```

## AI

#### Attention Impulsiveness (AI)

**AI1**

```{r, eval=FALSE}

data <- data %>% mutate(across(AI1:ER4, as.factor))

main.AI1 <- clmm(AI1 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```


```{r}
sum <- summary(main.AI1)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.AI1, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**AI2**

```{r, eval=FALSE}
main.AI2 <- clmm(AI2 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.AI2)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.AI2, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**AI3**

```{r, eval=FALSE}
main.AI3 <- clmm(AI3 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.AI3)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.AI3, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**AI4**

```{r, eval=FALSE}
main.AI4 <- clmm(AI4 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.AI4)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.AI4, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**AI5**

```{r, eval=FALSE}
main.AI5 <- clmm(AI5 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.AI5)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.AI5, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

## OV

#### Online Vigilance (OV)

**OV1**

```{r, eval=FALSE}
main.OV1 <- clmm(OV1 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.OV1)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.OV1, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**OV2**

```{r, eval=FALSE}
main.OV2 <- clmm(OV2 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.OV2 )
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.OV2, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**OV3**

```{r, eval=FALSE}
main.OV3 <- clmm(OV3 ~ group + time + group:time +
                    (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.OV3 )
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.OV3, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

## MT

#### Multitasking (MT)

**MT1**

```{r, eval=FALSE}
main.MT1 <- clmm(MT1 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.MT1)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.MT1, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**MT2**

```{r, eval=FALSE}
main.MT2 <- clmm(MT2 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.MT2)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.MT2, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**MT3**

```{r, eval=FALSE}
main.MT3 <- clmm(MT3 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.MT3)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.MT3, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**MT4**

```{r, eval=FALSE}
main.MT4 <- clmm(MT4 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.MT4)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.MT4, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

## ER

#### Emotion Regulation (ER)

**ER1**

```{r, eval=FALSE}
main.ER1 <- clmm(ER1 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.ER1)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.ER1, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**ER2**

```{r, eval=FALSE}
main.ER2 <- clmm(ER2 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.ER2)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.ER2, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**ER3**

```{r, eval=FALSE}
main.ER3 <- clmm(ER3 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.ER3)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.ER3, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

**ER4**

```{r, eval=FALSE}
main.ER4 <- clmm(ER4 ~ group + time + group:time +
                   (1 | student), data = data, Hess=TRUE, nAGQ=7)
```

```{r}
sum <- summary(main.ER4)
cf <- sum$coefficients %>% as.data.frame() 

cf[1:4, 1] <- cf[1:4, 1]*-1
cf[1:4, 3] <- cf[1:4, 3]*-1
rownames(cf)[1:4] <- c("4|5", "3|4", "2|3", "1|2")
cf %>% mutate(odd_ratio = exp(Estimate)) %>% 
  mutate_if(is.numeric, ~ round(., 3))

ggpredict(main.ER4, terms = c("time", "group")) %>% plot() + 
  scale_x_continuous(breaks = c(0, 1)) 
```

:::
